### ISSUE TITLE
You can interact with bottomView when topView is presented

### ISSUE THREAD

**Issue by IsaacXen** [foundry/NSViewControllerPresentation#3]
I've changed the `alphaValue` to `0.8` for a better demonstration.

![demo2](https://cloud.githubusercontent.com/assets/16833681/20783334/2ae8bf50-b7ce-11e6-9886-0236fd2cdf71.gif)

I can't find a way to solve this.

**Comment by foundry** [comment]
I've just added a fix. The storyboard version's presented viewController was incorrectly set to a default NSView. The MyView subclass has clickblockers. [See the explanation in the class](https://github.com/foundry/NSViewControllerPresentation/blob/master/NSViewControllerPresentations/MyView.m).

**Comment by IsaacXen** [comment]
great!
